### ISSUE TITLE
❌ Failed to fetch track details; maybe that track is age restricted on YouTube. Try playing any other.

### ISSUE THREAD

**Issue by neonhexit** [TheTeamVivek/YukkiMusic#14]
Hello, I installed the music bot, but I am getting the error in the title, ERROR in the terminal:

 [youtube+oauth2] 6tcxlHM3yqc: Sign in to confirm you're not a bot. This helps protect our community. Learn more
 
I'm getting the error

**Comment by Vivekkumar-IN** [comment]
@neonhexit Did you doing the oauth method for playing music
if yes so try again with another gmail

**Comment by Vivekkumar-IN** [comment]
cookies/oauth2 in this what are you using?

**Comment by neonhexit** [comment]
cookies.txt in repo

**Comment by Vivekkumar-IN** [comment]
@neonhexit [Comment out this](https://github.com/TheTeamVivek/YukkiMusic/blob/master/requirements.txt#L27) if you are using cookies

**Comment by neonhexit** [comment]
I don't know how to do it can you teach me

**Comment by Vivekkumar-IN** [comment]
Come on Telegram on @TheTeamvk

**Comment by KSKOP69** [comment]
> Hello, I installed the music bot, but I am getting the error in the title, ERROR in the terminal:
> 
> [youtube+oauth2] 6tcxlHM3yqc: Sign in to confirm you're not a bot. This helps protect our community. Learn more
> 
> I'm getting the error

use cookies
