### ISSUE TITLE
error when play music with youtube platform

### ISSUE THREAD

**Issue by fadhilarab47** [TheTeamVivek/YukkiMusic#3]
ERROR: [youtube] 83ntBBDC8Xs: Sign in to confirm you’re not a bot. This helps protect our community. Learn more 
how to solve this error when we are playing again via the /play command

**Comment by hakutakaid** [comment]
Use Cookie

**Comment by Vooyage21** [comment]
use heroku host if on vps use cookies

**Comment by Vivekkumar-IN** [comment]
beacause of yt-dlp
